Create status codes to errors types
miguel5g/todo-app pull request #38
Opened 2022-12-07 22:17 UTC by victorbr988

Eu criei um objeto contendo alguns tipos de códigos de erros que são utilizados dentro do app. Exportei no modo padrão para evitar possíveis erros quando se exporta como Default, como mudar o nome do objeto e esquecer de modificar em outros arquivos do código.

2022-12-07 22:26 UTC, miguel5g requested changes
Muito top! Mas poderia fazer apenas uma alteração? Colocar a variável `statusCodes`  com o S maiúsculo, já que ele é uma constante, tipo `StatusCodes`?

2022-12-07 22:31 UTC, victorbr988 commented
> Muito top! Mas poderia fazer apenas uma alteração? Colocar a variável `statusCodes` com o S maiúsculo, já que ele é uma constante, tipo `StatusCodes`?

Perfeito, vou alterar agora

2022-12-07 23:51 UTC, miguel5g approved these changes

2022-12-09 14:48 UTC, miguel5g approved these changes

2022-12-09 17:59 UTC, merged